### ISSUE TITLE
User positioning is the Queue is not reflected on unauth page list (Agencies and Organizations on the Waitlist) (PASS)

### ISSUE THREAD

**Issue by MHEBE3ET** [dotbc/dotbc-queue-site#5]
I moved user to the top of the Queue and it is not reflect on the Agencies and Organizations on the Waitlist
![untitled4](https://cloud.githubusercontent.com/assets/13591955/20863899/e66e7da0-b9a9-11e6-9c5c-dafdd1e725f8.png)

**Comment by MHEBE3ET** [comment]
![untitled5](https://cloud.githubusercontent.com/assets/13591955/20863900/eb1e20a8-b9a9-11e6-8946-1e2b79548d13.png)

**Comment by mateodelnorte** [comment]
Did you refresh the page? It doesn't pop in via a websocket. You have to refresh. 

That said, I added a secondary sort so the waitlist is now sorted by queue position, ascending, and the accepted are also sorted so that most recently accepted are higher.

Closing for now, as I can't repro, but reopen if needed.

**Comment by MHEBE3ET** [comment]
Pass
